### ISSUE TITLE
jsda sodir etilgan kamchiliklar

### ISSUE THREAD

**Issue by ozbeg** [UmarAbdurazzoq/Fizz-Buzz#1]
<img width="613" alt="Screen Shot 2020-11-10 at 11 21 19" src="https://user-images.githubusercontent.com/68459737/98635504-f03acb80-2346-11eb-9cbb-43d8bdef5d3a.png">
console logger qolib ketmagani yaxshi

<img width="1260" alt="Screen Shot 2020-11-10 at 11 22 24" src="https://user-images.githubusercontent.com/68459737/98635538-05aff580-2347-11eb-8b42-0e524922805b.png">
  

dasturda kerak bo'lmagan kommentlar kerak emas

<img width="474" alt="Screen Shot 2020-11-10 at 11 23 54" src="https://user-images.githubusercontent.com/68459737/98635736-59224380-2347-11eb-891b-bc980ee0bb40.png">

algoritma  xatoliklari bor 3ga bo'linsa va 5ga bo'linmasa deb olinishi kerak keyingisi esa 5ga bo'linsa va 3ga bo'linmasa deb olinishi kerak

**Comment by UmarAbdurazzoq** [comment]
xato ishlayabtimi yoki prosta sening yo'lingmi

**Comment by UmarAbdurazzoq** [comment]
har bitta xatolikni alohida issue da yozsang nur ustiga alo nur bo'lar edi

**Comment by ozbeg** [comment]
uzur xato yozibman

**Comment by UmarAbdurazzoq** [comment]
fix this issue thank you
